image: python:latest

test-job:
    stage: test
    before_script:
        - python3 -m venv $(pwd)
        - source ./bin/activate
        - python3 -m pip install pyyaml schema pytest flask
        - export PYTHONPATH=$(pwd)
        - export CLOCKBRIDGE_CONFIG_PATH=tests/testConfig.yaml
    script:
        - pytest --junitxml tests/results.xml tests/

    artifacts:
      when: always
      paths:
        - tests/
      reports:
        junit: tests/results.xml

deploy-prod:
  tags:
    - deploy
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: development
