image: python:latest

test-job:
    stage: test
    before_script:
        - python3 -m venv $(pwd)
        - source ./bin/activate
        - python3 -m pip install pyyaml schema pytest flask
        - export PYTHONPATH=$(pwd)
        - export CLOCKBRIDGE_CONFIG_PATH=tests/testConfig.yaml
    script:
        - pytest --junitxml tests/results.xml tests/

    artifacts:
      when: always
      paths:
        - tests/
      reports:
        junit: tests/results.xml

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi

#deploy-prod:
#  tags:
#    - deploy
#  stage: deploy
#  script:
#    - docker-compose up --build
#  environment: production
