image: docker:latest

test-job:
    stage: test
    before_script:
        - python3 -m venv $(pwd)
        - source ./bin/activate
        - python3 -m pip install pyyaml schema pytest flask
        - export PYTHONPATH=$(pwd)
        - export CLOCKBRIDGE_CONFIG_PATH=tests/testConfig.yaml
    script:
        - pytest --junitxml tests/results.xml tests/

    artifacts:
      when: always
      paths:
        - tests/
      reports:
        junit: tests/results.xml

docker-build:
  stage: build
  services:
    - docker:dind
  script:
    - docker-compose build
  before_script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash

deploy-prod:
  tags:
    - deploy
  stage: deploy
  script:
    - docker-compose up --detach
#  environment: production
