version: '3'
services:
  app:
    build: .
    volumes:
      - /opt/clockbridge:/clockbridge
    ports:      
      - "8080:8080"

  proxy:
    build: nginx
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - app
volumes:
  app:

